workDir: "app"
virtualEnv: "redash-virtualenv"
consulPath: "dse/redash-internal"
vaultDatabasePath: "dse/postgres/stage-dse-tools/redash_de/redash_de_application_api"
vaultApplicationPath: "dse/applications/redash_de"
grofersIOComponentPrefix: "redash-internal"
applicationHostName: "redash-internal-service-data.stage-ore-k8s.grofer.io"

frontend:
  replicaCount: 1
  resources:
    limits:
      cpu: "3000m"
      memory: "5Gi"
    requests:
      cpu: "1500m"
      memory: "3Gi"

service:
  sslCert: arn:aws:acm:us-west-2:050634864816:certificate/9048dfcc-6df0-4311-abf0-4650ef17e066
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0

celery:
  workers:
  - type: "beat"
    name: "celerybeat"
    replicaCount: 1
    concurrency:
    queueName:
    maxTaskPerChild:
    timeLimit:
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "0.5Gi"
  - type: "worker"
    name: "celerydefault"
    replicaCount: 1
    concurrency: 2
    queueName: "celery,queries,scheduled_queries,destination_sync"
    maxTaskPerChild: 10
    timeLimit: 300
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "0.5Gi"
