"""empty message

Revision ID: 0b7d34673388
Revises: 89bc7873a3e0
Create Date: 2021-04-09 21:12:18.716990

"""
from alembic import op
import sqlalchemy as sa
from redash.models import types


# revision identifiers, used by Alembic.
revision = '0b7d34673388'
down_revision = '89bc7873a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_type', sa.String(length=255), nullable=False),
    sa.Column('sync_duration', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('visualization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('options', types.Configuration(), nullable=False),
    sa.Column('last_destination_sync_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_destination_sync_id'], ['destination_sync_history.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visualization_id'], ['visualizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_is_archived'), 'destinations', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinations_is_archived'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_table('destination_sync_history')
    # ### end Alembic commands ###
