{{- if .Values.celery.flower.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name -}}-celeryflower
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name -}}-celeryflower
    component: {{ $.Release.Name -}}-taskserver
    grofers.io/service: redash
    grofers.io/component: {{ $.Values.grofersIOComponentPrefix -}}-celery-worker
    grofers.io/component-role: data-processing
    grofers.io/business-service: data-reporting
    grofers.io/team: data-engineering
    grofers.io/tribe: data

spec:
  replicas: 1
  selector:
    matchLabels:
      pod: {{ $.Release.Name -}}-celeryflower
  template:
    metadata:
      labels:
        pod: {{ $.Release.Name -}}-celeryflower
        app: {{ $.Release.Name -}}-celeryflower
        component: {{ $.Release.Name -}}-taskserver
        grofers.io/service: redash
        grofers.io/component: {{ $.Values.grofersIOComponentPrefix -}}-celery-worker
        grofers.io/component-role: data-processing
        grofers.io/business-service: data-reporting
        grofers.io/team: data-engineering
        grofers.io/tribe: data
    spec:
      initContainers:
      - name: consul-template
        image: 442534439095.dkr.ecr.ap-southeast-1.amazonaws.com/infra/consul-template:v1.0.0
        env:
        - name: CONSUL_ADDR
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        args: [
            '-template', '/config-template/env.ctml:/config/.env',
            '-once',
            # '-log-level=trace',
          ]
        volumeMounts:
        - name: {{ $.Release.Name -}}-configmap
          mountPath: /config-template
        - name: {{ $.Release.Name -}}-config
          mountPath: /config
      containers:
      - name: {{ $.Release.Name -}}-celeryflower
        image: {{ $.Values.image }}
        command: ['bin/run', '/{{- $.Values.workDir -}}/{{- $.Values.virtualEnv -}}/bin/celery', 'flower', '--app=redash.worker', '--loglevel=INFO']
        ports:
        - name: "flower-port"
          containerPort: 5555
        resources:
{{ toYaml .Values.celery.flower.resources | indent 10 }}
        volumeMounts:
        - name: {{ $.Release.Name -}}-config
          mountPath: /{{- $.Values.workDir -}}/.env
          subPath: .env
        env:
          - name: REDASH_STATSD_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
      volumes:
      - name: {{ $.Release.Name -}}-configmap
        configMap:
          name: {{ $.Release.Name -}}-configmap
      - name: {{ $.Release.Name -}}-config
        emptyDir: {}
{{- end -}}
