{{- if .Values.celery.flower.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name -}}-celeryflower-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "grofers.io/service=redash,grofers.io/component={{- $.Values.grofersIOComponentPrefix -}}-elb,grofers.io/component-role=loadbalancer,grofers.io/business-service=data-reporting,grofers.io/team=data-engineering,grofers.io/tribe=data"
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ $.Release.Name -}}-celeryflower-service
    grofers.io/service: redash
    grofers.io/component: {{ $.Values.grofersIOComponentPrefix -}}-elb
    grofers.io/component-role: loadbalancer
    grofers.io/business-service: data-reporting
    grofers.io/team: data-engineering
    grofers.io/tribe: data
spec:
  type: LoadBalancer
  ports:
  - port: 5555
    name: flower-port
  selector:
    pod: {{ $.Release.Name -}}-celeryflower
{{- end -}}
